<?php
/**
 * @file
 * Code for the Landportal Extra feature.
 */

include_once 'landportal_extra.features.inc';
/**
 * @file
 * Landportal extra module
 *
 * Original work by: WESO (http://weso.es/)
 * Drupal refactoring: Jules <jules@ker.bz>
 */

module_load_include('inc', 'landportal_extra', 'landportal_extra.blocks');

/**
 * Default block configuration for the Landportal
 *  - main-menu goes in header
 *  - hide 'power-by' (default drupal footer)
 *  - Search form goes in section_header
 *  - user login form: hide
 */
function landportal_extra_block_info_alter(&$blocks, $theme, $code_blocks) {
  $region = 'header';
  if ($theme == 'landportal') {
    $region = 'section_header';
    foreach (array('main-menu', 'user-menu') as $m) {
      $blocks['system'][$m]['status'] = TRUE;
      $blocks['system'][$m]['region'] = 'header';
      $blocks['system'][$m]['visibility'] = BLOCK_VISIBILITY_NOTLISTED;
      $blocks['system'][$m]['pages'] = "user\nuser/login\nuser/register\nuser/password";
    }
    $blocks['locale']['language']['status'] = TRUE;
    $blocks['locale']['language']['region'] = 'header';
    $blocks['locale']['language']['weight'] = 3;
    $blocks['locale']['language']['title'] = '<none>';

    $blocks['menu']['user-signin']['status'] = TRUE;
    $blocks['menu']['user-signin']['region'] = $region;
    $blocks['menu']['user-signin']['visibility'] = BLOCK_VISIBILITY_LISTED;
    $blocks['menu']['user-signin']['pages'] = "user\nuser/login\nuser/register\nuser/password";

    $blocks['search']['form']['status'] = TRUE;
    $blocks['search']['form']['region'] = $region;
    $blocks['search']['form']['visibility'] = BLOCK_VISIBILITY_NOTLISTED;
    $blocks['search']['form']['pages'] = "user\nuser/login\nuser/register\nuser/password";

    // Disable Drupal default block
    foreach (array('powered-by', 'navigation') as $m) {
      $blocks['system'][$m]['status'] = FALSE;
      $blocks['system'][$m]['region'] = '';
    }
    $blocks['user']['login']['status'] = FALSE;
    $blocks['user']['login']['region'] = '';
  }
  return $blocks;
}
/**
 * Hide default user tabs
 */
function landportal_extra_menu_alter(&$items) {
  $items['user']['type'] = MENU_CALLBACK;
  $items['user/register']['type'] = MENU_CALLBACK;
  $items['user/password']['type'] = MENU_CALLBACK;
  $items['user/login']['title'] = 'User account';
}
