<?php



/**
 * Creates a form override to edit an existing or create a new campaign and use a specific input format --> mailchimp_campaign .
 *
 */
 
function mailchimp_seg_custom_form_alter(&$form, &$form_state, $form_id) {
  
  if($form_id == 'mailchimp_user_list_edit_campaign_form') {
  
   $form['mailchimp_content'] = array(
      '#title' => t('HTML Content'),
      '#type' => 'text_format',
      '#required' => FALSE,
      '#format' => 'mailchimp_campaign',
      '#rows' => '20',
      '#weight' => 6,
    );
  
  return $form;
  
  }
   

    
  
}

?>