<?php
/**
 * Provide facilities to manage the Land Portal
 */
include_once 'landportal_bo.views_default.inc';
/**
 * Add a 'Manage' tab to Admin > structure > taxonomy page
 */
function landportal_bo_menu() {
    /* $items['admin/structure/taxonomy/terms'] = array( */
    /*     'title' => 'Manage terms', */
    /*     'type' => MENU_LOCAL_TASK, */
    /*     'access arguments' => array('administer taxonomy'), */
    /*     'weight' => 12, */
    /* ); */
    $items['admin/structure/taxonomy/terms/topics'] = array(
        'title' => 'Manage Topics',
        'type' => MENU_LOCAL_TASK,
        'access arguments' => array('administer taxonomy'),
        'weight' => 10,
        'callback' => 'systems_view_data',
        //'page callback' => 'node_page_view',//admin_views_taxonomy_terms_topics',
        'page arguments' => array('admin/structure/taxonomy/terms/topics'),
    );
    $items['admin/people/moderate'] = array(
        'title' => 'Pending account',
        'type' => MENU_LOCAL_TASK,
        'access arguments' => array('administer users'),
        'weight' => 9,
        //'page callback' => 'XXX_admin_view_XXX',
    );
    return $items;
}
