<?php
/**
 * USAID importer feeds
 *
 * Author: Jules Clement <jules@ker.bz>
 * Date: Oct. 2015
 */

include_once 'landlibrary_importers_usaid.feeds_importer.inc';
include_once 'landlibrary_importers_usaid.feeds_tamper.inc';

function landlibrary_importers_usaid_ctools_plugin_api($module = '', $api = '') {
    if ($module == "feeds_tamper" && $api == "feeds_tamper_default") {
        return array("version" => "2");
    }
    if ($module == "feeds" && $api == "feeds_importer_default") {
        return array("version" => "1");
    }
}
