<?php
/**
 * @file
 * Provides a harvester for oai-pmh targets.
 *
 * @copyright Copyright(c) 2015 AK 
 * @license GPL v2 http://www.fsf.org/licensing/licenses/gpl.html
 * @author Papoutsis Georgios at agro-know IKE 
 */

 
function oai_harvester_menu() {
  $items = array();
  

$items['start-harvester'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Start IFPRI harvester FROM date UNTIL date', //page title
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('oai_harvester_form'), //put the name of the form here
    'access callback' => TRUE
  );
  return 

$items;
}

function oai_harvester_form($form, &$form_state) {
  
 $form['oai_target'] = array(
    '#type' => 'textfield', //you can find a list of available types in the form api
    '#title' => 'OAI-PMH target url',
    '#size' => 100,
    '#description' => 'the OAI-PMH target url from which you want to harvest',
    '#maxlength' => 160,
    '#required' => TRUE, //make this field required
  );

 $form['oai_set'] = array(
    '#type' => 'textfield', //you can find a list of available types in the form api
    '#title' => 'OAI-PMH set',
    '#size' => 50,
    '#description' => 'the OAI-PMH set from which you want to harvest',
    '#maxlength' => 160,
    '#required' => TRUE, //make this field required
  );




 $form['from_date'] = array(
    '#type' => 'textfield', //you can find a list of available types in the form api
    '#title' => 'From date',
    '#size' => 20,
    '#description' => 'the date from which you want to harvest like 2014-9-10',
    '#maxlength' => 40,
    '#required' => TRUE, //make this field required 
  );
  
  $form['until_date'] = array(
    '#type' => 'textfield', //you can find a list of available types in the form api
    '#title' => 'Until date',
    '#description' => 'the date until  you want to harvest like 2014-11-22',
    '#size' => 20,
    '#maxlength' => 40,
    '#required' => TRUE, //make this field required 
  );

/*
$form['start_tracking'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable'),
    '#default_value' => isset($settings['start_tracking']) ? $settings['start_tracking'] : FALSE,
    '#description' => t('Harvest from IFPRIs OAI-PMH publications'),
  );

*/
  

$form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Submit!'),    
  );
  
  return $form;
}


 
function oai_harvester_form_submit($form, &$form_state) {

  global $user;
  if ($user->uid ) {
        
     //$form_state['values']['url'],
    if(!empty($form_state['values']['until_date']) && !empty($form_state['values']['from_date']) )
    {
     start_ifpri_harvesting($user, $form_state['values']['from_date'], $form_state['values']['until_date'],$form_state['values']['oai_target'],$form_state['values']['oai_set']);
    }else {
     print "please set dates";  
    }
    
  }else {
  // Not logged in
    print "Please go to login page";
  //  die("please login");
  }

}
 
 

//https://api.drupal.org/api/drupal/modules%21user%21user.module/7
//http://www.apaddedcell.com/an-introduction-user-stats-module-drupal
function start_ifpri_harvesting(&$user, &$from ,&$until,&$oaitarget, &$oaiset){ 
//    $from='2014-9-10';
//    $until='2014-12-21';
    $script="/var/www/htdocs/IFPRI_dates";
	
	
      //	Check if user is loggedin
     if($user->uid){
      $message = 'Ifpri harvesting has started from ' . $from . ' to  ' . $until . 'Please do not refresh the page until the harvesting finish. ';
      drupal_set_message(t('Ifpri harvesting has started from ' . $from . ' to  ' . $until . 'Please do not refresh the page until the harvesting finish. '), 'status');
     
      watchdog( 'oai_harvester', $message, $variables = NULL, $severity = WATCHDOG_NOTICE, $link = NULL );
   echo  exec('cd /root/IFPRI_harvester; /root/IFPRI_harvester/oai__php_harvester '. $from . ' ' . $until . ' ' . $oaitarget . ' ' . $oaiset,$result );

      $message = 'Ifpri harvesting done from ' . $from . ' to ' . $until . ' at ' . date("Y-m-d h:i:sa") ;
      drupal_set_message(t('OAI harvesting from ' . $from . ' to ' . $until . ' Records harvested: '. $result[2]), 'status');  
      watchdog( 'oai_harvester', $message . 'Records harvested: ' . $result[2], $variables = NULL, $severity = WATCHDOG_NOTICE, $link = NULL );
   }//end if

 return;
 
} 
