<?php
/**
 * @file
 * Code for the Landlibrary IFPRI Importer feature.
 */

include_once 'landlibrary_importers_ifpri.feeds_importer.inc';
include_once 'landlibrary_importers_ifpri.feeds_tamper.inc';

function landlibrary_importers_ifpri_ctools_plugin_api($module = '', $api = '') {
    if ($module == "feeds_tamper" && $api == "feeds_tamper_default") {
        return array("version" => "2");
    }
    if ($module == "feeds" && $api == "feeds_importer_default") {
        return array("version" => "1");
    }
}
