<?php
/**
 * @file
 * landbook_country.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function landbook_country_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-landbook_country-body'.
  $field_instances['node-landbook_country-body'] = array(
    'bundle' => 'landbook_country',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Country narative',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => 1,
    'settings' => array(
      'display_summary' => 0,
      'entity_translation_sync' => FALSE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-landbook_country-field_countries'.
  $field_instances['node-landbook_country-field_countries'] = array(
    'bundle' => 'landbook_country',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Bind this narrative to the proper country.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_countries',
    'label' => 'Country',
    'required' => 1,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-landbook_country-field_indicators'.
  $field_instances['node-landbook_country-field_indicators'] = array(
    'bundle' => 'landbook_country',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Pre-selected indicators for this country',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'i18n_taxonomy',
        'settings' => array(),
        'type' => 'i18n_taxonomy_term_reference_link',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_indicators',
    'label' => 'Indicators',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'taxonomy',
      'settings' => array(
        'autocomplete_path' => 'taxonomy/autocomplete',
        'size' => 60,
      ),
      'type' => 'taxonomy_autocomplete',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Bind this narrative to the proper country.');
  t('Body');
  t('Country');
  t('Country narative');
  t('Indicators');
  t('Pre-selected indicators for this country');

  return $field_instances;
}
