<?php
/**
 * FAOLEX importer feeds
 *
 * Author: Jules Clement <jules@ker.bz>
 * Date: Oct. 2015
 */

include_once('importer_faolex.feeds_importer.inc');
include_once('importer_faolex.feeds_tamper.inc');

function importer_faolex_ctools_plugin_api($module = '', $api = '') {
    if ($module == "feeds_tamper" && $api == "feeds_tamper_default") {
        return array("version" => "2");
    }
    if ($module == "feeds" && $api == "feeds_importer_default") {
        return array("version" => "1");
    }
}

/**
 * Override FeedsCrawlerPattern form
 * Change 'pattern' field to textarea (allowing longer uri params)
 *
 * TODO: check if there is a improv. req/bug in plugin issue list on drupal
 * create + submit a patch (no reason to limit query string to 128 char.
 *    -this is very limitating-)
 */
/* function importer_faolex_form_alter(&$form, &$form_state, $form_id) { */
/*     if (isset($form['feeds']) && isset($form['feeds']['FeedsCrawlerPattern'])) { */
/*         //dpm($form['feeds']['FeedsCrawlerPattern'], 'Pattern detected'); */
/*         $form['feeds']['FeedsCrawlerPattern']['pattern']['#type'] = 'textarea'; */
/*     } */
/* } */

/* function importer_faolex_feeds_before_import(FeedsSource $source) { */
/*     // See feeds_rules module's implementation for an example. */
/*     dpm($source); */
/*     $source_config = $source->getConfigFor(); */
/*     dpm($source_config, 'SConfig'); */
/* } */

/* // hook FeedsCrawlerPatterm */
/* function importer_faolex_feeds_after_parse(FeedsSource $source, FeedsParserResult $result) { */
/*     dpm($source); */
/*     dpm($result); */
/*   // For example, set title of imported content: */
/*     //$result->title = 'Import number ' . my_module_import_id(); */
/* } */

/**
 * Implements hook_feeds_plugins().
 */
function importer_faolex_feeds_plugins() {
    $path = drupal_get_path('module', 'importer_faolex');
    $info = array();
    $info['FeedsCrawlerPatternCleaner'] = array(
        'name' => 'Cleaner Pattern fetcher',
        'description' => 'Provides paging using a URL pattern AND clean return.',        
        'handler' => array(
            /* 'class' => 'FeedsCrawlerPattern', */
            /* 'parent' => 'FeedsCrawlerBase', */
            'parent' => 'FeedsCrawlerPattern',
            'class' => 'FeedsCrawlerPatternCleaner',
            'file' => 'FeedsCrawlerPatternCleaner.php',
            'path' => $path,
        ),
    );
    return $info;
}
