<?php
/**
 * @file
 * Landportal footer block
 *
 * Original work by: WESO (http://weso.es/)
 * Drupal refactoring: Jules <jules@ker.bz>
 */

function landportal_footer_block_info() {
  $blocks['landportal_footer'] = array(
    'info' => t('Landportal footer'),
    'status' => TRUE,
    'region' => 'footer',
  );
  //$blocks['landportal_footer']['info'] = t('Footer for LP');
  return $blocks;
}

function landportal_footer_block_configure($delta='') {
   $form = array();
  
   switch($delta) {
   case 'landportal_footer' :
     $form['text_body'] = array(
       '#type' => 'text_format',
       '#title' => t('the Landportal footer text'),
       '#default_value' => variable_get('landportal_footer_text', 'Landportal | (c)'),
     );
     break;
   }
   return $form;
 }

function landportal_footer_block_save($delta = '', $edit = array()) {
  switch($delta) {
  case 'landportal_footer' :
    // Saving the WYSIWYG text      
    variable_set('landportal_footer_text', $edit['text_body']['value']);
    break;
  }
}

function landportal_footer_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
  case 'landportal_footer':
    $text = variable_get('landportal_footer_text', '');
    //$block['subject'] = t('LPFooter');
    $block['content'] = $text;
    break;
  }
  return $block;
}

/* /\** Default block configuration for landbook-menu */
/*  * @TODO bug: pages & visibility doesn't appear in drupal landdebate menu block setting page, though it seems to work */
/*  *\/ */
/* function landdebate_block_info_alter(&$blocks, $theme, $code_blocks) { */
/*   if ($theme == 'landportal' && ! $blocks['menu'][$GLOBALS['landdebate_menu']]['status']) { */
/*   //print_r(dpm($blocks['menu'][$GLOBALS['landdebate_menu']])); */
/*     $blocks['menu'][$GLOBALS['landdebate_menu']]['status'] = TRUE; */
/*     $blocks['menu'][$GLOBALS['landdebate_menu']]['region'] = 'highlighted'; */
/*     $blocks['menu'][$GLOBALS['landdebate_menu']]['visibility'] = BLOCK_VISIBILITY_LISTED; */
/*     $blocks['menu'][$GLOBALS['landdebate_menu']]['pages'] = "debate\ndebate/\*"; */
/*   } */
/*   return $blocks; */
/* } */
