<?php
/**
 * @file
 * Code for the Land Community feature.
 */

include_once 'landcommunity.features.inc';

/**
 * Land Community
 * This module provides Organization and People functionnalities to the Landportal.
 *
 * Original work by: Jules Clement <jules@ker.bz>
 * Created on: July 2015
 */

function landcommunity_help($path, $arg) {
  switch ($path) {
  case "admin/help#landcommunity":
    return '<p>' . t("Community functionnalities for the Landportal") . '</p>'
      ;
    break;
  }
}
