<?php
/**
 * @file
 * Code for the Land Community feature.
 */

include_once 'landcommunity.features.inc';

/**
 * Land Community
 * This module provides Organization and People functionnalities to the Landportal.
 *
 * Original work by: Jules Clement <jules@ker.bz>
 * Created on: July 2015
 */

function landcommunity_help($path, $arg) {
  switch ($path) {
  case "admin/help#landcommunity":
    return '<p>' . t("Community functionnalities for the Landportal") . '</p>'
      ;
    break;
  }
}
function landcommunity_entity_info_alter(&$entity_info) {
    /* dpm($entity_info['user']['view modes']); */
    /* dpm($entity_info); */
    foreach (array ('user', 'profile2') as $entity) {
        $entity_info[$entity]['view modes']['teaser'] = array(
            'label' => t('Teaser'),
            'custom settings' => TRUE,
        );
    }
    $entity_info['profile2']['view modes']['full'] = array(
            'label' => t('User account (Full)'),
            'custom settings' => TRUE,
    );
}