<?php
/**
 * @file
 * Code for the Land Community feature.
 */

include_once 'landcommunity.features.inc';

/**
 * Land Community
 * This module provides Organization and People functionnalities to the Landportal.
 *
 * Original work by: Jules Clement <jules@ker.bz>
 * Created on: July 2015
 */

function landcommunity_help($path, $arg) {
  switch ($path) {
  case "admin/help#landcommunity":
    return '<p>' . t("Community functionnalities for the Landportal") . '</p>'
      ;
    break;
  }
}

/**
 * Implements hook_default_profile2_type().
 */
function landcommunity_default_profile2_type() {
  $items = array();
  $items['main'] = entity_import('profile2_type', '{
    "userCategory" : true,
    "userView" : true,
    "type" : "main",
    "label" : "Public profile",
    "weight" : "0",
    "data" : { "registration" : 0 },
    "rdf_mapping" : []
  }');
  return $items;
}

function landcommunity_enable() {
    // Field are added to profile2 main in *features.field_instance.inc
    //field_create_instance($instance);
}


/**
 * Alter a 'default' view from another module
 */
/* function landcommunity_views_default_views_alter(&$views) { */
/*     if (array_key_exists('VIEW_NAME', $views)) { */
/*         $view = $views['VIEW_NAME']; */
/*         /\* Display: Page *\/ */
/*         $handler = $view->new_display('page', 'Page', 'page_1'); */
/*         $handler->display->display_options['defaults']['arguments'] = FALSE; */
/*         $handler->display->display_options['path'] = 'path'; */
/*         // Stuff me */
/*         // ... */
/*     } */
/* } */


/* ctools_include('landdebate.menu', 'landdebate'); */
/* function landdebate_menu() { */
/*   $items = array(); */
/*   landdebate_menu_admin($items); */
/*   landdebate_menu_build($items); */

/*   // Landdebate frontend */
/*   $items['debate'] = array( */
/*     'title'		=> 'Landdebate', */
/*     'menu_name'		=> 'main-menu', */
/*     //'type'              => MENU_NORMAL_ITEM, */
/*     'access callback'	=> TRUE, */
/*     'page callback'	=> 'drupal_goto', */
/*     'page arguments'	=> array('debate/news'), */
/*   ); */
/*   return $items; */
/* } */

