<?php
/**
 * @file
 * This module provide an interface to the landbook section of the Landportal.
 *
 * The Landportal landbook
 *
 * Original work by: WESO (http://www.weso.es/)
 * Drupal refactoring: Jules <jules@ker.bz>
 */

require_once(drupal_get_path('module', 'landbook').'/utils/database_helper.php');
require_once(drupal_get_path('module', 'landbook').'/utils/cache_helper.php');

$GLOBALS['landbook_menu'] = 'landbook-menu';

function landbook_help($path, $arg) {
  switch ($path) {
  case "admin/help#landbook":
    return '<p>' . t("Landbook section of the Landportal") . '</p>'
      . '<p>'. t("This come with a (header) Block, customised View(s) and a landbook main-menu item").'</p>'
      . '<p>'. t("The Landbook is composed of different modules: catalog, countries, indicators, regions, reuse, sources, widgets").'</p>'
      ;
    break;
  }
}

function landbook_theme() {
  $struct = array(
    'variables' => array(
      'meta' => NULL,
      'data' => NULL,
    ),
  );
  return array(
    'regions'   => $struct,
    'countries' => $struct,
    'country'   => $struct,
    /* 'file' => 'countries.tpl.php', */
    /* 'path' => drupal_get_path('module', 'landbook').'/theme', */
  );
}

function landbook_add_js_css() {

  //drupal_add_js('misc/jquery.js');
  //drupal_add_js('misc/jquery.once.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/jquery-2.1.0.min.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/bootstrap.min.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/util.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/canvg.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/rgbcolor.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/language.js');
  //drupal_add_js(drupal_get_path('module', 'landbook').'/js/search.js');
  //drupal_add_js(drupal_get_path('module', 'landbook').'/js/ajax.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/StackBlur.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/seedrandom.min.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/country_chart_options.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/wesCountry.min.js');

  drupal_add_css(drupal_get_path('module', 'landbook').'/js/libraries/wesCountry.min.css');
}

function landbook_menu() {
  $items = array();

  // Admin section
  $items['admin/config/landbook'] = array(
    'title'             => 'Landbook',
    'description'       => 'Configure the landbook',
    'postition'         => 'right',
    'weight'            => -4,
    'page callback'	=> 'system_admin_menu_block_page',
    'access arguments'  => array('administer site configuration'),
    'file'              => 'system.admin.inc',
    'file path'         => drupal_get_path('module', 'system'),
  );
  $items['admin/config/landbook/settings'] = array(
    'title'             => 'Landbook settings',
    'description'       => 'Base landbook configuration',
    'page callback'	=> 'drupal_get_form',
    'page arguments'	=> array('landbook_admin_settings'),
    'access arguments'  => array('administer site configuration'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'landbook.admin.inc',
    'file path'         => drupal_get_path('module', 'landbook').'/includes'
  );

  // Landbook frontend
  $items['book'] = array(
    'title'		=> 'landbook',
    'menu_name'		=> 'main-menu',
    'access callback'	=> TRUE,
    'type'              => MENU_NORMAL_ITEM,
    'page callback'	=> 'landbook_regions',
    'page arguments'	=> array(),
    'file'              => 'regions.inc',
    'file path'         => drupal_get_path('module', 'landbook').'/modules'
  );

  // Automatically build Landbook menu according to available modules
  ctools_include('landbook.menu', 'landbook');
  landbook_menu_build($items);

  return $items;
}

function landbook_block_info_alter(&$blocks, $theme, $code_blocks) {

  if ($theme == 'landportal') {
    $blocks['menu'][$GLOBALS['landbook_menu']]['status'] = TRUE;
    $blocks['menu'][$GLOBALS['landbook_menu']]['region'] = 'highlighted';
    $blocks['menu'][$GLOBALS['landbook_menu']]['visibility'] = BLOCK_VISIBILITY_LISTED;
    $blocks['menu'][$GLOBALS['landbook_menu']]['pages'] = "book\nbook/*";
  }
  return $blocks;
}