<?php
/**
 * @file
 * This module provide an interface to the landbook section of the Landportal.
 *
 * The Landportal landbook
 *
 * Original work by: WESO (http://www.weso.es/)
 * Drupal refactoring: Jules <jules@ker.bz>
 */

require_once(drupal_get_path('module', 'landbook').'/utils/database_helper.php');
require_once(drupal_get_path('module', 'landbook').'/utils/cache_helper.php');

$GLOBALS['landbook_menu'] = 'landbook-menu';
$GLOBALS['landbook_sections'] = array('regions', 'countries', 'catalog', 'indicators', 'sources', 'reuse', 'widgets');

ctools_include('landbook.menu', 'landbook');

function landbook_help($path, $arg) {
  switch ($path) {
  case "admin/help#landbook":
    return '<p>' . t("Landbook section of the Landportal") . '</p>'
      . '<p>'. t("This come with a (header) Block, customised View(s) and a landbook main-menu item").'</p>'
      . '<p>'. t("The Landbook is composed of different modules: catalog, countries, indicators, regions, reuse, sources, widgets").'</p>'
      ;
    break;
  }
}

function landbook_theme() {
  $struct = array(
    'variables' => array(
      'meta' => NULL,
      'data' => NULL,
    ),
  );
  return array(
    'regions'   => $struct,
    'countries' => $struct,
    'country'   => $struct,
  );
}

function landbook_add_js_vars($countryCode=NULL) {
  global $language;
  // TODO: should come from a module variable (manageable via in admin/settings)
  $ajaxURL = '/'.drupal_get_path('module', 'landbook').'/ajax';
  drupal_add_js(array('landbook' => array(
                                      'ajaxURL'         => $ajaxURL,
                                      'countryCode'     => $countryCode,
                                      'languageCode'    => $language->language,
                )), 'setting'
  );
}

function landbook_add_js_css() {
  //drupal_add_js('misc/jquery.js');
  //drupal_add_js('misc/jquery.once.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/jquery-2.1.0.min.js');
  //drupal_add_js(drupal_get_path('module', 'landbook').'/js/search.js');
  //drupal_add_js(drupal_get_path('module', 'landbook').'/js/ajax.js');

  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/bootstrap.min.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/util.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/language.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/canvg.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/rgbcolor.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/StackBlur.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/seedrandom.min.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/country_chart_options.js');
  drupal_add_js(drupal_get_path('module', 'landbook').'/js/libraries/wesCountry.min.js');

  drupal_add_css(drupal_get_path('module', 'landbook').'/js/libraries/wesCountry.min.css');
  //drupal_add_css(drupal_get_path('theme', 'landportal').'/css/bootstrap.min.css');
}

function landbook_menu() {
  $items = array();
  landbook_menu_admin($items);
  // Automatically build Landbook menu according to available modules
  landbook_menu_build($items);

  // Landbook main-menu link
  $items['book'] = array(
    'title'		=> 'Landbook',
    'menu_name'		=> 'main-menu',
    'type'              => MENU_NORMAL_ITEM,
    'access callback'	=> TRUE,
    'page callback'	=> 'landbook_regions',
    'page arguments'	=> array(),
    'file'              => 'regions.inc',
    'file path'         => drupal_get_path('module', 'landbook').'/modules'
  );
  $translatables['book'][] = t('Landbook');
  return $items;
}

/**
 * Force landbook-menu block to display on landportal theme
 */
function landbook_block_info_alter(&$blocks, $theme, $code_blocks) {
  if ($theme == 'landportal') {
    $blocks['menu'][$GLOBALS['landbook_menu']]['status'] = TRUE;
    $blocks['menu'][$GLOBALS['landbook_menu']]['region'] = 'section_header';
    $blocks['menu'][$GLOBALS['landbook_menu']]['visibility'] = BLOCK_VISIBILITY_LISTED;
    $blocks['menu'][$GLOBALS['landbook_menu']]['pages'] = "book\nbook/*";
  }
  return $blocks;
}
